### ISSUE TITLE
Registrar el Complemento Carta Porte versión 2.0

### ISSUE THREAD

**Issue by eclipxe13** [phpcfdi/sat-ns-registry#3]
El 2021-10-26 el SAT libreró la información técnica de la nueva versión:
http://omawww.sat.gob.mx/tramitesyservicios/Paginas/complemento_carta_porte.htm

**Comment by eclipxe13** [comment]
Según el estándar técnico, el archivo XSD se encuentra en <http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte20/CartaPorte20.xsd>, pero al momento (2021-10-18 13:54:00 GMT-5) responde con `403 Forbidden`:

```
curl -sv http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte20/CartaPorte20.xsd
*   Trying 2600:9000:2048:8c00:10:a6f6:bf80:93a1:80...
* Connected to www.sat.gob.mx (2600:9000:2048:8c00:10:a6f6:bf80:93a1) port 80 (#0)
> GET /sitio_internet/cfd/CartaPorte20/CartaPorte20.xsd HTTP/1.1
> Host: www.sat.gob.mx
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Connection: keep-alive
< Date: Thu, 28 Oct 2021 18:52:48 GMT
< Server: AmazonS3
< X-Cache: Error from cloudfront
< Via: 1.1 161e201905562c50ef334eaaeadc7017.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: QRO50-C1
< X-Amz-Cf-Id: bYdG6rHGG4cZvmoTw3yC320Qtna-J3iroxm9afvGJYbIvDor83DC8Q==
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host www.sat.gob.mx left intact
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>W7GV8466GATWBNCE</RequestId><HostId>Ddd+1wOxfpN5mu9itLrMu2G1i8Jol+QkoWojYAB/fEhLJtH72VJPnrNxK6Qr98+hCT9uwRahAG0=</HostId></Error>
```

**Comment by eclipxe13** [comment]
Confirmo que sigue igual esta situación, las ligas devuelven `403 Forbidden`:
- <http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte20/CartaPorte20.xsd>
- <http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte20/CartaPorte20.xslt>

No se debe incluir hasta que el origen se encuentre disponible.

**Comment by ramelp** [comment]
Las ligas están disponibles en:

http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd
http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte/CartaPorte.xslt
http://omawww.sat.gob.mx/tramitesyservicios/Paginas/documentos/CartaPorte20.pdf

**Comment by eclipxe13** [comment]
@ramelp muchas gracias!!

La dirección XSD no era la que había publicado, es
<http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd> y ya se encuentra disponible.

La dirección `http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte/CartaPorte.xslt` no es para Carta Porte 2.0, es la de Carta Porte 1.0. La dirección documentada <http://omawww.sat.gob.mx/tramitesyservicios/Paginas/documentos/CartaPorte20.xslt> aún no se incluye en el generador de la cadena de origen de CFDI 3.3 <http://www.sat.gob.mx/sitio_internet/cfd/3/cadenaoriginal_3_3/cadenaoriginal_3_3.xslt>, por lo tanto, los contenidos de Carta Porte 2.0 no son tomados en cuenta en la cadena de origen.

Mi idea es no agregar la información de Carta Porte 2.0 al listado hasta tener la ruta del XSLT agregada al archivo `cadenaoriginal_3_3.xslt`. O bien, agregar el registro **sin la url de el archivo XSLT**.

**Comment by gam04** [comment]
Hola comunidad. 
Intercambiando algunos mensajes, me comentan que el XSLT de la version 2.0 de CartaPorte no se reflejara en `cadenaoriginal_3_3.xslt` hasta el día de su liberación (es decir el 1 de diciembre) ya que la versión 1.0 es la que sigue vigente para su emisión en producción.

**Comment by eclipxe13** [comment]
Hola, quién te comenta?

Liberar la URL nunca ha sido un impedimento para el CFDI.

En las liberaciones de complementos generalmente se integran desde antes de su fecha de vigencia. No es problema porque los PAC antes de firmar simplemente validan la fecha de emisión del CFDI y la versión del complemento, si el complemento está presente antes de la fecha de vigencia lo rechazan. Mientras tanto, los implementadores no tenemos problema para generar, e incluso validar, la cadena de origen generada por el XSLT.

Sin embargo, voy a abrir un PR para agregar el complemento sin la dirección del XSLT.
